version: "3.1"
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "4545:4545"
    environment:
      MYSQL_DATABASE: mi4web
      MYSQL_ROOT_PASSWORD: root 
      
    volumes:
      - datafiles:/var/lib/mysql
      - ./mi4web.sql:/docker-entrypoint-initdb.d/mi4web.sql
    restart: always

volumes:
  datafiles: