version: "3.3"
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mi4web
      MYSQL_ROOT_PASSWORD: mi4web 
    restart: always
    volumes:
      - ./data/db:/var/lib/mysql