version: '3.5'

services:
  orthanc:
    image: jodogne/orthanc-plugins:1.9.7
    hostname: orthanc
    volumes:
      # Config
      - ./config/orthanc.json:/etc/orthanc/orthanc.json:ro
      # Persist data
      - ./volumes/orthanc-db/:/var/lib/orthanc/db/
    ports:
      - '8082:4242' # DICOM
      - '8083:8042' # Web
    restart: unless-stopped
    networks:
      - all

networks:
  all:
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/16
