version: "3.1"
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3001:3306"
    environment:
      MYSQL_DATABASE: SIO_P1
      MYSQL_ROOT_PASSWORD: root 
      
    volumes:
      - datafiles:/var/lib/mysql
      - ./sqlitraining.sql:/docker-entrypoint-initdb.d/sqlitraining.sql
    restart: always

volumes:
  datafiles: